#!/bin/bash
set -e
export DEBIAN_FRONTEND=noninteractive

echo "🚀 Starting Installation..."

set -e # Exit on error

echo "------------------------------------------------"
echo "🚀 Starting Kubernetes Worker Node Preparation..."
echo "------------------------------------------------"

sudo apt-get update -y

# Updating /etc/hosts for connection
if ! grep -q "ANSIBLE MANAGED HOSTS" /etc/hosts; then
  echo -e "\n# BEGIN ANSIBLE MANAGED HOSTS\n$(hostname -I | awk '{print $1}') $(hostname).example.com $(hostname)\n# END ANSIBLE MANAGED HOSTS" | sudo tee -a /etc/hosts > /dev/null
fi

# Disabling swap 
sudo swapoff -a
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# Adding kernel modules 
sudo modprobe overlay
sudo modprobe br_netfilter

cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf > /dev/null
overlay
br_netfilter
EOF

# Setting up sysctl parameters
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf > /dev/null
net.bridge.bridge-nf-call-iptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward = 1
EOF
sudo sysctl --system

# Installing necessary dependencies (Removed firewalld)
sudo apt-get install -y curl gnupg software-properties-common ca-certificates lsb-release conntrack socat ipset

# Adding Docker/Containerd Repo
sudo mkdir -p /etc/apt/keyrings
sudo chmod 0755 /etc/apt/keyrings

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
sudo chmod 0644 /etc/apt/keyrings/docker.asc

echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update -y

# Installing Containerd AND Docker Engine simultaneously
sudo apt-get install -y containerd.io docker-ce docker-ce-cli docker-buildx-plugin docker-compose-plugin

# Generating clean containerd config for Kubernetes CRI
sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

# Force restart containerd to apply CRI changes
sudo systemctl daemon-reload
sudo systemctl restart containerd
sudo systemctl enable containerd

# Enable and Start Docker
sudo systemctl enable docker
sudo systemctl start docker

# Add default ubuntu user to docker group securely
sudo usermod -aG docker ubuntu

# Kubernetes Setup 
sudo rm -f /etc/apt/sources.list.d/kubernetes.list
sudo rm -f /etc/apt/keyrings/kubernetes-apt-keyring.asc

# Downloading K8s GPG key
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key | sudo tee /etc/apt/keyrings/kubernetes-apt-keyring.asc > /dev/null
sudo chmod 0644 /etc/apt/keyrings/kubernetes-apt-keyring.asc

# Adding Kubernetes repository
echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null

# Installing K8s components
sudo apt-get update -y
sudo apt-get install -y kubelet kubeadm kubectl

# Preventing K8s packages from being upgraded automatically
sudo apt-mark hold kubelet kubeadm kubectl

echo "------------------------------------------------"
echo "✅ Worker Node Preparation Complete!"
echo "Docker version: $(docker --version)"
echo ""
echo "To join this worker to the cluster, SSH into this instance and run the join command generated by your master node."
echo "------------------------------------------------"